### ISSUE TITLE
error while importing pyfdb

### ISSUE THREAD

**Issue by devarajun** [ecmwf/pyfdb#4]
Hi, I have created a python environment and followed the installation steps. The installation is successful. But while `import pyfdb` I get the following error:

devaraju@uan02:/project/project_462000048/devaraju/EasyBuild/modules/LUMI/22.08/C> python
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyfdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/users/devaraju/.local/lib/python3.10/site-packages/pyfdb/__init__.py", line 1, in <module>
    from .pyfdb import *
  File "/users/devaraju/.local/lib/python3.10/site-packages/pyfdb/pyfdb.py", line 100, in <module>
    lib = PatchedLib()
  File "/users/devaraju/.local/lib/python3.10/site-packages/pyfdb/pyfdb.py", line 46, in __init__
    ffi.cdef(self.__read_header())
  File "/users/devaraju/.local/lib/python3.10/site-packages/pyfdb/pyfdb.py", line 77, in __read_header
    with open(os.path.join(os.path.dirname(__file__), "processed_fdb.h"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/users/devaraju/.local/lib/python3.10/site-packages/pyfdb/processed_fdb.h'

Could you please help me in resolving this error.

Thanks

**Comment by TomHodson** [comment]
Hey @devarajun, did you ever manage to solve this? Does it still occur?

**Comment by tbkr** [comment]
Feel free to reopen, if the issue still occurs.
